# PHP CircleCI 2.0 configuration file for Laravel 5.5 and Laravel Dusk by Wes Mahler
# Author wesmahler.com
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3.3

    working_directory: ~/laravel

    steps:
      - checkout

      - run:
          name: Setup Laravel testing environment variables for CircleCI test
          command: cp .env.circleci .env

      -run: apt install php7.3-bcmath

      - run:
          name: Update composer to latest version
          command: sudo composer self-update

      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
            - composer-v1-
      - run: composer install -n --prefer-dist --ignore-platform-reqs
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      - run: touch /tmp/testing.sqlite3
      - run:
          name: Migrate Laravel Database
          command: php artisan migrate --force

      - run: vendor/bin/phpunit
